config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :index]
  post "contacts/import", to: "contacts#import"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "contacts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
require "csv"

class Contact < ApplicationRecord
  attr_accessor :invalid_iso_birth_date
  attr_accessor :invalid_credit_card
  belongs_to :user

  NAME_VALIDATION_REGEX = /^[a-zA-Z\d\s-]*$/
  PHONE_VALIDATION_REGEX = /\(\+[0-9]{2}\) [0-9]{3}(-| )[0-9]{3}(-| )[0-9]{2}(-| )[0-9]{2}/

  validate :date_format
  validate :credit_card_validation
  validates :name, format: {
    with: NAME_VALIDATION_REGEX,
    message: 'no special characters, only letters and numbers',
    multiline: true
  }
  validates :phone, format: {
    with: PHONE_VALIDATION_REGEX,
    message: "phone numbers must be in '(+00) 000 000 00 00' or '(+00) 000-000-00-00' formats"
  }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: { scope: :user_id }
  
  validates_presence_of :name, :email, :birth_date, :phone, :address, :credit_card, :franchise

  def self.import(file, column_names, user)
    column_names = column_names.delete_if { |key, value| value.empty? }
    CSV.foreach(file, encoding: 'iso-8859-1:utf-8', headers: true) do |row|
      data = {
        name: row[column_names[:name] || "name"],
        email: row[column_names[:email] || "email"],
        birth_date: row[column_names[:birth_date] || "birth_date"],
        phone: row[column_names[:phone] || "phone"],
        address: row[column_names[:address] || "address"],
        credit_card: row[column_names[:credit_card] || "credit_card"],
        user_id: user.id
      } 
      contact = Contact.new(data)
      unless contact.save
        ErrorLog.create data: data, message: contact.errors.full_messages.join(", ")
      end
    end
  end

  def birth_date=(value)
    begin
      Date.iso8601(value) if value.present?
      super(value)
    rescue Date::Error
      @invalid_iso_birth_date = true
    end
  end
  
  def credit_card=(number)
    detector = CreditCardValidations::Detector.new(number)
    self.franchise = detector.brand.to_s
    @invalid_credit_card = true unless self.franchise && detector.valid?(self.franchise)
    number = "*" * (number.size - 4) + number[-4, 4] if number && number.size > 4
    super(number)
  end
  
  private
  def date_format
    errors.add(:birth_date, :invalid, message: "invalid ISO 8601 date") if @invalid_iso_birth_date
  end
  
  def credit_card_validation
    errors.add(:credit_card, :invalid, message: "invalid credit card") if @invalid_credit_card
  end
end

app/models/error_log.rb
class ErrorLog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contacts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @contacts = current_user.contacts.paginate(page: params[:page], per_page: 10)
  end

  def new
    @contact = Contact.new
  end

  def import
    Contact.import(import_params[:contacts_file], import_params[:columns], current_user)

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "File is being processed" }
    end
  end

  private
    
  def import_params
    params.permit(:contacts_file, columns: [:name, :email, :birth_date, :phone, :address, :credit_card])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= form_tag({action: :import}, multipart: true) do %>
   <div class="field">
     <%= label_tag :contacts_file %>
     <%= file_field_tag :contacts_file %>
   </div>

   <div class="field">
     <%= label_tag :name %>
     <%= text_field_tag "columns[name]" %>
   </div>
   <div class="field">
     <%= label_tag :email %>
     <%= text_field_tag "columns[email]" %>
   </div>
   <div class="field">
     <%= label_tag :birth_date %>
     <%= text_field_tag "columns[birth_date]" %>
   </div>
   <div class="field">
     <%= label_tag :phone %>
     <%= text_field_tag "columns[phone]" %>
   </div>
   <div class="field">
     <%= label_tag :address %>
     <%= text_field_tag "columns[address]" %>
   </div>
   <div class="field">
     <%= label_tag :credit_card %>
     <%= text_field_tag "columns[credit_card]" %>
   </div>
   <div class="actions">
      <%= submit_tag 'Submit' %>
   </div>
<% end %>

app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contacts</h1>

<div id="contacts">
  <table style="width:100%">
    <tr>
      <th>Company</th>
      <th>Contact</th>
      <th>Country</th>
    </tr>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.birth_date %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= contact.credit_card %></td>
        <td><%= contact.franchise %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= will_paginate @posts %>

<%= link_to "Import Contacts", new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvProccessing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>